# Generated by Django 4.0.2 on 2022-02-03 20:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название блюда')),
                ('content', models.TextField(verbose_name='Описание блюда')),
                ('weight', models.IntegerField(verbose_name='Вес блюда')),
                ('image', models.ImageField(upload_to='dishes/')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_code', models.CharField(max_length=4, verbose_name='Пин-код')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('order_date', models.DateTimeField(verbose_name='Время заказа')),
                ('is_done', models.BooleanField(default=False, verbose_name='В процессе')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menuapi.menu')),
                ('order_owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menuapi.room')),
            ],
        ),
    ]
