# Generated by Django 4.0.2 on 2022-02-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_sum',
            field=models.IntegerField(default=0, verbose_name='Сумма заказа'),
        ),
    ]
