# Generated by Django 4.0.2 on 2022-02-03 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuapi', '0002_order_total_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_sum',
        ),
    ]
